### ISSUE TITLE
Still need to load LOINC and hp.obo files?

### ISSUE THREAD

**Issue by tulachin** [pnrobinson/loinc2hpoMiner#13]
I am able to execute the app on Windows 10, but after that can't do much. I remember from a previous version that it was necessary to lead certain files. Is that still the case?
When building the app, the terminal prints out statements about not loading those files (or a particular user), so it reverts to the default.

Would appreciate some orientation regarding this.

**Comment by pnrobinson** [comment]
We could set up a zoom meeting to agree on a way forward. If you could paste in the error messages you see that would be useful.

**Comment by tulachin** [comment]
And after searching for a particular LOINC code, this is the stack:
<img width="951" alt="Untitled1" src="https://user-images.githubusercontent.com/12535179/143929807-1f345b80-419e-4be8-9f1b-bca3c0f30b04.png">
<img width="951" alt="Untitled2" src="https://user-images.githubusercontent.com/12535179/143929809-d7718883-14a4-4cbd-9e77-fd902a68fa2a.png">

**Comment by pnrobinson** [comment]
@tulachin I have added some code to catch these issues and show a warning, but I think that you need to go to the configuration menu and download some files. I will add this information to the README, which needs to have this information. I think things should work then.

**Comment by pnrobinson** [comment]
See the new setup section in the README please

**Comment by tulachin** [comment]
Thank you for that update! I tried locating the configuration menu on the app's GUI, but didn't see it. Unfortunately, can't drag/move the window around. I expect being able to do the rest of the steps once this is resolved.
<img width="958" alt="miner_gui" src="https://user-images.githubusercontent.com/12535179/144471344-013682af-fddc-4694-9f14-a16e2e1871e9.png">

**Comment by pnrobinson** [comment]
It looks as if the top of the app is getting cut off. Is it possible your lap top has a vertical resolution of 800? That would explain this. It might be possible to control-mouse drag the app downwards, but it will not be fun to use the app with this resolution. I am developing the app with a 2560 x 1600 MacBook and this probably you would need a vertical resolution of at least 1000 to be happy with the app.

**Comment by morales-felix** [comment]
Laptop screen resolution is 1920x1080. If I could drag the GUI, I could use it on my bigger screen.

**Comment by morales-felix** [comment]
Problem somehow solved: Something odd with having my laptop connected to an external monitor. When loading without being connected to an external monitor, the app works.
